# Generated by Django 2.0.5 on 2018-06-18 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('votes', models.IntegerField(default=1)),
                ('amazon_url', models.URLField()),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
