# Generated by Django 2.0.5 on 2018-06-20 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='game_images/'),
            preserve_default=False,
        ),
    ]
